### ISSUE TITLE
where are the SD card contents?

### ISSUE THREAD

**Issue by greysAcademicCode** [Ultimaker/Meta#1]
Is there a repo that contains the contents of the SD card shipped with the Ultimaker2?

**Comment by oliv3r** [comment]
I belive all designs should be on YouMagine. But you are right, having a 
page with all YouMagine links would be quite helpful.

To start the list (I don't have the sd card handy right now) top of my head:

https://www.youmagine.com/designs/coffin-s-half-hour-cube
https://www.youmagine.com/designs/ultimaker-robot


On 03-09-15 12:23, Grey Christoforo wrote:
>
> Is there a repo that contains the contents of the SD card shipped with 
> the Ultimaker2?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Ultimaker/Meta/issues/1>.
>

-- 
Met vriendelijke groeten, Kind regards, 与亲切的问候

Olliver Schinagl
Research & Development
Ultimaker B.V.

**Comment by nallath** [comment]
There is no repo that holds them. They are spread over multiple sites (as oliv3r already mentioned).

**Comment by daid** [comment]
The SD card comes with a text file that lists the origin of all files.
